# Generated by Django 5.1.1 on 2024-11-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sbd',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
