# Generated by Django 5.1.1 on 2024-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('nam', 'Nam'), ('nữ', 'Nữ'), ('khác', 'Khác')], default='khác', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
