# Generated by Django 5.1.1 on 2024-09-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionresult',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='position',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='team',
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='robot.registration'),
        ),
    ]
