# Generated by Django 5.1.1 on 2024-11-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_competition_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
