# Generated by Django 5.1.1 on 2024-09-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_competition_notification_sponsor_exam_feedback_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
