# Generated by Django 5.1.1 on 2024-09-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_remove_competitionresult_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kits/')),
            ],
        ),
        migrations.RemoveField(
            model_name='kit',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='image',
        ),
        migrations.AddField(
            model_name='kit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='images',
            field=models.ManyToManyField(related_name='kits', to='robot.kitimage'),
        ),
    ]
