# Generated by Django 5.1.1 on 2024-11-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_alter_competition_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='competitions/videos/'),
        ),
    ]
