# Generated by Django 5.1.1 on 2024-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
