# Generated by Django 5.1.1 on 2024-09-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_kitimage_remove_kit_competition_remove_kit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='images',
        ),
        migrations.AddField(
            model_name='kitimage',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='robot.kit'),
        ),
    ]
