# Generated by Django 5.1.1 on 2024-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_alter_competition_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
