# Generated by Django 5.1.1 on 2024-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_alter_userprofile_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competition_images/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
