# Generated by Django 5.1.1 on 2024-09-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_competition_image_alter_competition_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='max_participants',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
