# Generated by Django 5.1.1 on 2024-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_alter_competition_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
