# Generated by Django 5.1.1 on 2024-09-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_kit_main_image_kitdetail_delete_kitimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='main_image',
        ),
        migrations.AddField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kits/', verbose_name='Hình ảnh đính kèm'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên bộ kit'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giá bán'),
        ),
        migrations.DeleteModel(
            name='KitDetail',
        ),
    ]
