# Generated by Django 5.1.1 on 2024-09-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_remove_kit_main_image_kit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Giá bán'),
        ),
    ]
