# Generated by Django 5.1.1 on 2024-09-24 11:29

import robot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_kitimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='competition',
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/', validators=[robot.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chưa xem'), ('Reviewed', 'Đã xem'), ('Resolved', 'Đã giải quyết')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('contest', 'Cuộc thi'), ('result', 'Kết quả'), ('kit', 'Bộ kit'), ('other', 'Khác')], default='other', max_length=20),
        ),
    ]
