# Generated by Django 5.1.1 on 2024-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_remove_feedback_competition_feedback_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
