# Generated by Django 5.1.1 on 2024-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_remove_feedback_status_feedback_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('Cuộc thi', 'Cuộc thi'), ('Kết quả', 'Kết quả'), ('Bộ thiết bị', 'Bộ thiết bị'), ('Khác', 'Khác')], default='other', max_length=20),
        ),
    ]
