# Generated by Django 5.1.1 on 2024-10-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0014_competition_guide_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='guide_file',
        ),
        migrations.CreateModel(
            name='GuideFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='competition_guides/')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_files', to='robot.competition')),
            ],
        ),
    ]
