# Generated by Django 5.1.1 on 2024-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0015_remove_competition_guide_file_guidefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_robot_competition_experience',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_competitor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='elo_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Học sinh thi đấu'), ('coach', 'Huấn luyện viên')], default='student', max_length=10),
        ),
    ]
