# Generated by Django 5.1.1 on 2024-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_remove_customuser_has_robot_competition_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='first_prize_award',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='first_prize_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='potential_award',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='potential_points',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='competition',
            name='second_prize_award',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='second_prize_points',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='competition',
            name='third_prize_award',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='third_prize_points',
            field=models.IntegerField(default=6),
        ),
    ]
