# Generated by Django 5.1.1 on 2024-10-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_remove_competition_first_prize_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidefile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
