# Generated by Django 5.1.1 on 2024-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0019_guidefile_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidefile',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
