# Generated by Django 5.1.1 on 2024-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0020_guidefile_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidefile',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
