# Generated by Django 5.1.1 on 2024-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0021_guidefile_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='participants_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
