# Generated by Django 5.1.1 on 2024-10-31 04:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0022_competition_location_competition_participants_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='start_date',
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_end_date',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.CreateModel(
            name='CompetitionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=255)),
                ('schedule', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='robot.competition')),
            ],
        ),
    ]
