# Generated by Django 5.1.1 on 2024-10-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0023_remove_competition_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='round_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CompetitionRound',
        ),
    ]
