# Generated by Django 5.1.1 on 2024-10-31 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0024_competition_round_name_competition_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='round_name',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='schedule',
        ),
        migrations.CreateModel(
            name='CompetitionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='robot.competition')),
            ],
        ),
    ]
