# Generated by Django 5.1.1 on 2024-11-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0025_remove_competition_round_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='match_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='robot.competitionround'),
        ),
        migrations.AddField(
            model_name='competitionround',
            name='num_matches',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competitionround',
            name='scoring_method',
            field=models.CharField(choices=[('highest_score', 'Điểm cao nhất trong các lượt'), ('total_score', 'Tổng điểm các lượt')], default='total_score', max_length=50),
        ),
        migrations.CreateModel(
            name='CompetitionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='robot.competition')),
            ],
        ),
    ]
