# Generated by Django 5.1.1 on 2024-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0026_competitionresult_match_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionround',
            name='scoring_method',
            field=models.CharField(blank=True, choices=[('highest_score', 'Điểm cao nhất trong các lượt'), ('total_score', 'Tổng điểm các lượt')], default='total_score', max_length=50, null=True),
        ),
    ]
