# Generated by Django 5.1.1 on 2024-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0027_alter_competitionround_scoring_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionround',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='round',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='score',
        ),
        migrations.AddField(
            model_name='competition',
            name='groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='competition',
            name='rounds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='CompetitionGroup',
        ),
        migrations.DeleteModel(
            name='CompetitionRound',
        ),
    ]
