# Generated by Django 5.1.1 on 2024-11-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0028_remove_competitionround_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='robot.team'),
            preserve_default=False,
        ),
    ]
