# Generated by Django 5.1.1 on 2024-11-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0029_remove_registration_user_registration_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='robot.team'),
        ),
    ]
