# Generated by Django 5.1.1 on 2024-11-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0032_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='robot.competition'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='group_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='robot.participant'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='robot.team'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionresult',
            unique_together={('competition', 'team', 'round_number', 'group_number')},
        ),
    ]
