# Generated by Django 5.1.1 on 2024-11-07 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0034_remove_competitionresult_participant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='prize_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='ranking_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='result_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='round_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='score',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='robot.team'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('nam', 'Nam'), ('nữ', 'Nữ')], default='nam', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0352844893', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='competitionresult',
            name='round_number',
        ),
    ]
